org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=craft_config
mod.name=Craft Config Library
mod.group=net.tricube
mod.version=1.1.8
mod.channel_tag=
mod.authors=tricube
mod.contributors=
mod.license=MIT
mod.description=A Configuration library that supports presets and built-in keybinds.
mod.sources_url=https://github.com/tricube3/craft-config-lib
mod.issues_url=https://github.com/tricube3/craft-config-lib/issues

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]

publish.modrinth=pqvUbuK1
publish.curseforge=1530219
publish.github=false
